[package]
name = "hello-solana"
version = "0.1.0"
description = "Native Solana Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.16.24"

[dev-dependencies]
solana-program-test = "1.16.24"
solana-sdk = "1.16.24"